--[[ #include "src/config/constants.lua" ]]
-- src/config/models.lua is included unconditionally near the top of plugin.lua
-- (needed by GetProperties/GetControlLayout at design time too), so it is not
-- re-included here.
--[[ #include "src/config/inputs.lua" ]]
--[[ #include "src/core/logger.lua" ]]
--[[ #include "src/core/protocol.lua" ]]
--[[ #include "src/core/tcp.lua" ]]
--[[ #include "src/device/device.lua" ]]
--[[ #include "src/device/zones.lua" ]]
--[[ #include "src/device/channels.lua" ]]
--[[ #include "src/ui/ui.lua" ]]
--[[ #include "src/ui/events.lua" ]]
--[[ #include "src/main.lua" ]]